hoverinc/hover-javascript

src/config/tsconfig.json

This seems to get in the way quite often during development trial and error and kinda falls more in the domain of linting in my opinion.

Disable `noUnusedLocals` setting in TypeScript configuration

---

src/scripts/__tests__/__snapshots__/lint.js.snap
src/scripts/__tests__/lint.js
src/scripts/lint.js

The lint script was filtering file arguments passed to `eslint` to just JavaScript files causing it to miss TypeScript linting issues found on `precommit` entirely because `lint-staged` passes the staged files to `hover-scripts lint` as file arguments. This adds TypeScript files to the filter code.
Before:
```shell
hover-scripts lint file1.ts file2.tsx
```
↓
```shell
eslint
```
After:
```shell
hover-scripts lint file1.ts file2.tsx
```
↓
```shell
eslint file1.ts file2.tsx
```

Don't filter out TypeScript files from ESLint CLI args

---

package.json
yarn.lock

Upgrade Prettier to `2.0.5`. The motivation for this, aside from generally staying up to date, came from a bug I encountered when processing MDX: https://github.com/prettier/prettier/issues/6943.

Upgrade Prettier

---

.prettierrc
src/config/helpers/eslint.js
src/config/jest.config.js

- Allow `devDependencies` in the **e2e** directory
- Include tests in the **e2e** directory (must have test extension, e.g: `*.(spec|test).ts`)

Initial support for e2e test directory

---

src/config/jest.config.js

Match tests with `.test.*` suffix in `test/` directory.

Match tests with suffix extension in 'test/' directory

---

src/config/helpers/eslint.js

I'm also considering just adding `**/*.config.js`...

Allow `devDependencies` in Prettier configuration

---

src/scripts/__tests__/__snapshots__/commit.js.snap
src/scripts/__tests__/commit.js
src/scripts/commit.js

Put band-aid in place for bug that cropped up when invoking `hover-scripts commit` from `yarn commit`
Also use `require.resolve` to resolve 'commitizen' path for use in `bootstrap`ing prompt adapter to make resolution more resilient and remove the dependency on `node_modules` directory.

Fix commit script

---

src/config/eslintrc-react.js
src/config/eslintrc.js
src/config/helpers/eslint.js

- Default `parserOptions.project` **@typescript-eslint** setting with glob (`./**/*/tsconfig.json`) instead of just `./tsconfig.json` so all `tsconfig.json`'s are included by default
- Expose `buildConfig` exports from `@hover/javascript/eslint` and `@hover/javascript/eslint-react`
- Add `tsProjects` option on `buildConfig` to allow `parserOptions.project` to be set externally, e.g:
```js
const { buildConfig } = require('@hover/javascript/eslint');
module.exports = {
extends: buildConfig({ tsProjects: ['./tsconfig.json', './packages/**/*/tsconfig.json'],
rules: {
// ...
}
}
```

Expose ESLint config builder + TypeScript projects option

---

codefresh.yml
package.json

The `ci-after-success` script handles both Codecov reporting and releases, but it was only running on `master` and `next` and therefore was not publishing coverage reports from PRs.

Upload coverage reports from pull requests

---

src/config/eslintrc-react.js
src/config/eslintrc.js
src/config/helpers/eslint.js

This reverts commit 77bb2d0f6ddd7e955c2d6b6d226168dd8ab762f3.

Revert "feat: expose 'builders' and `tsProjects` option from ESLint config"

---

.github/dependabot.yml

Apparently it has a 15 character max...

⚙ Shorten Dependabot development dependencies prefix

---

src/config/helpers/eslint.js

All this time we've been loading the plugin without enabling any of the rules...

Enable React Hooks recommended rules

---

api.d.ts
api.js
commitlint.config.js
package.json
src/api/__mocks__/prettier.js
src/api/__tests__/__snapshots__/api.js.snap
src/api/__tests__/api.js
src/api/format.js
src/api/index.js
src/config/prettierrc.js
src/tsconfig.json
yarn.lock

- Add `api` package entry point
- Expose a pre-configured version of Prettier's `format` API
- Add `tsc` to build process to start outputting selective definitions via JSON type annotations

Expose Prettier `format` API

---

.eslintignore

These will always be package entries which shouldn't need linting and furthermore break the build sometimes on the `import/no-unresolved` rule when linting happens before a build is complete as they forward exports from modules in the `dist` directory which is created during the build.

💚 Ignore *.d.ts files at the project root

---

.gitignore
src/config/lintstagedrc.js
src/scripts/__tests__/__snapshots__/lint.js.snap
src/scripts/__tests__/lint.js
src/scripts/lint.js

Remove file filtering behavior from lint command so it can be used like eslint with glob patterns
Updated tests.  
Updated lintstagedrc.js to only run lint on .js(x), .ts(x) files to simulate same behavior

feat(scripts/lint): allow glob arguments to linter

---

src/config/helpers/eslint.js

Typescript has its own mechanism for validating prop types and the react proptypes are redundant

feat(config/eslintrc): turn off prop types validation for typescript

---

src/config/helpers/eslint.js

Only override the `'react/prop-types'` rule in React projects (has `'react'` dependency or extends `@hover/javascript/eslint-react`). Currently the **react/prop-types** override in `parserOptions` throws an error in non-React projects as the default behavior there is to extend the non-React version of **eslint-config-airbnb-typescript/base** and therefore the **react/prop-types** rule does not exist in that case.

Only override prop types rule in React projects

---

src/config/helpers/eslint.js

This is necessary to mark 'dangling promises' as intentionally dangling, see: https://github.com/typescript-eslint/typescript-eslint/blob/v4.3.0/packages/eslint-plugin/docs/rules/no-floating-promises.md#ignorevoid.

Allow void statements

---

src/tsconfig.json

Oops, we were compiling `__mocks__` directories.

Exclude mocks from TypeScript build

---

commitlint.config.js
src/api/__tests__/commit.js
src/api/commit.js
src/config/commitlint.config.js

Adds `commit` API with some helpers for configuring **commitlint**, e.g:
```js
const { ls, scopes } = require('@hover/javascript/api/commit');
module.exports = {
extends: ['@hover/javascript/commitlint'],
rules: {
'scope-enum': [
1,
'always',
[
...scopes.build(),
...ls.configs('./config'),
],
],
},
}
```

✨ Add commit API with commitlint helpers

---

package.json
src/config/jest.config.js

- Switch from `ts-jest` preset to `ts-jest/presets/js-with-ts` in order to support JS files when using `ts-jest`
- Add `--copy-files` to build script to fix missing `tsconfig.json` in release

Fix missing TypeScript configuration and Jest transform for JavaScript

---

api.d.ts
api.js
api/commit.d.ts
api/commit.js
api/index.d.ts
api/index.js

We were only exposing the index of `api`. We need to expose `api/commit` as an entry point as well to get at the named exports.

Update `api` entry points to expose `commit` module

---

src/config/helpers/build-eslint.js
src/config/helpers/eslint.js

Allow `devDependencies` in `*.config.{js,ts}`.

Allow development dependencies in all config files

---

src/scripts/__tests__/__snapshots__/ci-after-success.js.snap
src/scripts/ci-after-success.js

The `--extends` CLI flag for the `semantic-release` flag was outside of quotes
and therefore was doing nothing.

🐛 Fix quoting in release command

---

package.json

Kent's ESLint configuration (`eslint-config-kentcdodds`) should be a `devDependency` as we only use it to format this codebase in order to preserve compatibility with the upstream repo. The configuration we provide externally is not based on this configuration.

➡️ Make KCD ESLint configuration a devDependency

---

package.json
yarn.lock

🔪 Remove **resolve**, it must have been around for the build scripts I removed in 5.0.

🔪 Remove unnused resolve dependency

---

src/config/helpers/build-eslint.js

To ensure compatibility with JavaScript without the need for `parserOptions`
and a `tsconfig.json` we need to make sure any type-aware rules are disabled for JavaScript files. Some new type-aware rules were added in a recent update of **@typescript-eslint/eslint-plugin** so we need to disable them.

🐛 Fix JavaScript linting compatibility issue

---

src/config/helpers/build-eslint.js

Allow some `any` here and there in tests (disable `@typescript-eslint/unsafe-returns` and `@typescript-eslint/unsafe-assignment` in test files).

🤷🏻 Allow unsafe (any) assignment + returns in tests

---

README.md
eslint/react.js

Expose the React-specific ESLint preset at `@hover/javascript/eslint/react` (we'll deprecate `@hover/javascript/eslint-react` soon). Also add documentation for the React preset.

Add consistent entrypoint for React ESLint configuration

---

README.md

Husky 5 has licensing restrictions for commercial projects as well as significant changes to how hooks are configured so make sure the Husky example in the `README.md` explicitly documents installing Husky 4.

📝 Update readme with Husky 4 stuff 😑

---

src/config/helpers/build-lint-staged.js
src/scripts/__tests__/__snapshots__/pre-commit.js.snap

Split up lint and test tasks in the built-in **lint-staged** configuration so that they will run in parallel.

✨ Parallelize lint + test tasks in lint-staged configuration

---

src/config/helpers/build-eslint.js

Allow `devDependencies` to be imported in the `test/` directory.

✨ Allow development dependencies in test directory

---

src/config/eslintrc-strict.js

Group `import { ... } from 'test/**'` imports with ESLint like we do for `src` and `assets`.

✨ Group test alias imports

---

package.json
src/config/jest.config.js
tsconfig.json
yarn.lock

- Add **ts-jest** and **tslib** as dependencies
- Use **ts-jest** automatically if `tsconfig.json` is found

✨ Fully automatic TypeScript testing

---

package.json
yarn.lock

Include TypeScript as a `dependency` as opposed to a `devDependency` now that we're bundling **ts-jest**.

🐛 Include TypeScript as a dependency (again)

---

src/scripts/__tests__/ci-after-success.js
src/scripts/ci-after-success.js

`GITHUB_REF` doesn't have a leading slash.

🐛 Fix branch parsing for GitHub actions

---

src/config/jest.config.js

Ignore `<rootDir>/dist` in relevant Jest configuration options.

✨ Ignore dist directory in Jest configuration

---

src/scripts/__tests__/__snapshots__/commit-msg.js.snap
src/scripts/__tests__/commit-msg.js
src/scripts/commit-msg.js

Arguments weren't actually being forwarded to **@commitlint/cli**... missed this due to snapshot based tests ☹.
- Fixes use case of actually passing `--edit $1` for example
- Also fixes passing a custom config via `--config`
✨ Also support Husky 6 by defaulting to `--edit` when no arguments are passed.

🐛 Fix argument forwarding for commit-msg script

---

src/run-script.js
src/scripts/__tests__/__snapshots__/commit.js.snap
src/scripts/__tests__/commit.js
src/scripts/commit.js

Update argument forwarding logic in `run-script` wrapper to dynamically find sub-script command and therefore pass the correct arguments to the script without hard-coding the script names. I was not aware of this hard-coded bit and therefore some scripts were receiving the sub-script command in their `process.argv` erroneously.
This removes the need for a workaround I had added while unaware of this issue and fixes the Husky 6 support in `commit-msg`.

🐛 Fix argument parsing

---

api/test.d.ts
api/test.js
src/api/__tests__/test.js
src/api/test.js
src/config/commitlint.config.js

- Use `lowercase` instead of `kebab-case` for **scope-case**
- Expose **ts-jest** `utils` at `@hover/javascript/api/test`

✨ Expose ts-jest utils API

---

api/test.js

Type definitions were pointing to the correct place, but `api/test` was not pointing to `/dist` correctly.

🐛 Fix test API entrypoint

---

src/config/tsconfig.json

Set `resolveJsonModule` to `true` by default in the exposed `tsconfig.json`.

✨ Resolve JSON modules by default in TypeScript configuration

---

src/api/test.js

Derp, was forwarding *ts-jest* exports with ESM instead of CommonJS.

🐛 Fix api/test again

---

.github/workflows/automerge.yml

- Use different GitHub token for automege updates (should fix issues with PR builds not running on update force pushes)
- Use a separate label to enable autoupdate of PRs

💚 Update auto-merge configuration

---

.babelrc.json
src/api/test.js

- Use ESM `*` to forward ts-jest exports (fixes `api/test`)
- Explicitly transpile to CommonJS to support aforementioned export

🐛 Actually fix export forwarding for test API"

---

src/tsconfig.json

The TypeScript compiler output was overwriting Babel's output which was
breaking... you guessed it, the fucking `api/test` entrypoint. This
should. fix. it. for. real.

🐛 Fix TypeScript build (yet another test API fix)

---

package.json
yarn.lock

Fixes `peerDependency` warning for Jest 27.

⬆️ Upgrade jest-watch-typeahead

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
README.md
package.json

- Migrate Husky configuration to 7.0 (Dependabot already upgraded it)
- Update Husky instructions in `README.md` for Husky 6+
- Add `prepare-commit-msg` hook to optionally support [git-duet](https://github.com/git-duet/git-duet)

🔧 Migrate Husky configuration + documentation to 6+

---

lint-staged.js
lint-staged/index.js
lint-staged/no-toc.js
package.json
src/config/helpers/build-lint-staged.js
src/config/lintstagedrc-no-toc.js
src/scripts/__tests__/__snapshots__/pre-commit.js.snap
src/scripts/__tests__/pre-commit.js
src/scripts/pre-commit.js
src/utils.js
yarn.lock

- Add support for `--no-toc` flag in `pre-commit` script that disables DocToc.
- Add `/lint-staged/no-toc` variant of *lint-staged* configuration
- Add *cross-spawn* types
- Pull out relative path helper function `const hereRelative = relative(__dirname)`
- Pull out helper function for stripping arguments
- Fix type checking warnings in `scripts/pre-commit`

✨ Add support for disabling DocToc with a command flag

---

jest.config.js
src/config/jest.config.js

Because we're encapsulating the `ts-jest` dependency, there are cases where a package manager won't lift `ts-jest` to the root `node_modules` directory which prevents the preset from being loaded. Importing (`require('ts-jest/presets')`) the preset ensures it will always resolve, even when the dependency is nested, e.g: `./node_modules/@hover/javascript/node_modules/ts-jest`.

🐛 Ensure ts-jest preset is resolved

---

package.json

Update `files` field in `package.json` to correctly expose **@hover/javascript/lint-staged** entrypoint now that it is a folder and not just a single file.

🐛 Fix lint-staged entrypoint

---

src/config/jest.config.js

This reverts commit ea4489a9fe4cc946b28978d8bc7ce3131eef29d8.Reverts hoverinc/hover-javascript#511
The fix was intended to make the `jest.config.js` this package exports more resilient to `ts-jest` being installed in a nested `./node_modules` location, but it doesn't work and furthermore it breaks the `jest.config.js`.

Revert ts-jest preset change

---

src/config/helpers/build-eslint.js
src/config/helpers/test-match.js
src/config/jest.config.js
src/run-script.js
src/scripts/__mocks__/@hover/javascript/eslint.js
src/scripts/__tests__/__snapshots__/lint.js.snap
src/scripts/lint.js

Resolve ESLint plugins relative to **@hover/javascript** installation. This makes the ESLint configuration handle cases where package managers nest the ESLint dependencies in `node_modules/@hover/javascript/node_modules`.
- Move test match configuration into common helper

🐛 Resolve ESLint plugins relative to @hover/javascript

---

src/scripts/lint.js

Lood for `.eslintrc.yml` and `.eslintrc.yaml` when determining whether to use built-in ESLint configuration.

🐛 Include Yaml-based ESLint configs

---

package.json
src/config/jest.config.js
src/scripts/__tests__/__snapshots__/test.js.snap
src/scripts/__tests__/test.js
src/scripts/test.js
yarn.lock

Configure Jest with GitHub actions reporter when on running in the context of GitHub actions.
- Add **jest-github-actions-reporter**
- 🎨 Give test some room to breath, mock `env` entirely
- Enable `testLocationInResults`

✨ Report with GitHub actions reporter

---

eslint/react-strict.js
src/__tests__/index.js
src/config/__tests__/__snapshots__/eslintrc.js.snap
src/config/__tests__/eslintrc.js
src/config/eslintrc-react-strict.js
src/config/eslintrc-react.js
src/scripts/__tests__/ci-after-success.js
src/scripts/__tests__/commit-msg.js
src/scripts/__tests__/commit.js
src/scripts/__tests__/format.js
src/scripts/__tests__/lint.js
src/scripts/__tests__/pre-commit.js
src/scripts/__tests__/test.js
src/scripts/__tests__/validate.js
src/test/helpers/serializers.js

- refactor: move serializers into dedicated test helpers directory
- test(config/eslint): add snapshot coverage for ESLint configurations
- feat(config/eslint): disable `react/jsx-props-no-spreading`
- feat(config/eslint): add strict React ESLint configuration

✨ Add strict React ESLint configuration

---

src/utils.js

This addresses the 💥 in the `pre-commit` caused by upgrading Lint Staged to 12.x (pure ESM).
The `resolveBin` util was using `require('package-name/package.json')` to read the `bin` field of packages, but that blows up for ESM packages as an export map is required to define the package entrypoint and who's gonna add `package.json` as a package entry?

🐛 Fix bin resolution for ESM tools

---

src/__tests__/utils.js
src/utils.js

The previous `resolveBin` modification actually broke all scripts (including `validate` which is used on CI, which caused false positives for everything... and `ci-after-success` which caused several releases to fail silently).

🐛 Fix all scripts (I broke everything)

---

src/scripts/__tests__/pre-commit.js

Only the OS/shell should remove the quotes: https://github.com/yargs/yargs/issues/1324.
Since we're populating `process.argv` directly the quotes in the tests were treated as "inner quotes" (e.g: `'"some test command"'`). In actual usage the shell will remove quotes from something like `hover-scripts pre-commit --test-command='some test command'`.

✅ Fix custom test command tests with Yargs fix

---

src/config/__tests__/__snapshots__/eslintrc.js.snap
src/config/helpers/build-eslint.js

It makes the interface less stable. If you change a method between instance and class, you have to change all invocations. Whether or not it uses `this` is an implementation detail that should not matter for the interface

✨ Disable class-methods-use-this rule

---

src/scripts/__tests__/__snapshots__/format.js.snap
src/scripts/format.js

My previous change to the **lint-staged** configuration is pretty useless without this.

🐛 Include JSON5 in format allow list glob

---

src/api/__tests__/__fixtures__/ls/dirs/.gitignore
src/api/__tests__/commit.js
src/api/commit.js

Update **commitlint** helper function, `ls.dirs()` to support excluding directories via an option and exclude `node_modules` folders by default.
> ⚠️  BREAKING CHANGE: `ls.dirs()` from `api/commit` now takes an options object as the second parameter instead of a `prefix`. If you're using a prefix you'll need to make the following change:
```ts
// Before
ls.dirs('./packages', 'my-prefix');
// After
ls.dirs('./packages', { prefix: 'my-prefix' });
```
> ⚠️ BREAKING CHANGE: `ls.dirs()` now excludes `node_modules` directories by default. If for some reason you want to include \`node_modules\`, you'll need to explicitly set \`exclude\` to \`null\`:
```ts
// Before
ls.dirs('./packages');
// After
ls.dirs('./packages', { exclude: null });
```

✨ Add exclude option to commitlint helper

---

src/config/helpers/build-lint-staged.js
src/scripts/__tests__/__snapshots__/pre-commit.js.snap

I'm not sure if this is new behavior or somehow I've just now started running into this... anyways, the `pre-commit` script is failing when `--findRelatedTests` turns up with no tests, so it seems we need to also pass `--passWithNoTests` to prevent failures when no related tests are found.

🐛 Don't fail pre-commit when no related tests are found

---

package.json
src/config/helpers/build-lint-staged.js
src/config/tsconfig.json
src/scripts/__tests__/__snapshots__/pre-commit.js.snap
tsconfig.json
yarn.lock

Upgrade all **commitlint** dependencies.
Move the "canonical" shared `tsconfig.json` from `src/config/tsconfig.json` to the root of the repository.
> For consistency, up until now, the shared TypeScript configuration has lived in `src/config` with all of the other shared configurations that this package provides. For all of the other configurations we're able to simple re-export the configuration at the project root to provide it to consumers at `require('@hover/javascript/[config]')`. Because the TypeScript configuration is JSON, however, we were using `extends` instead of re-exporting. This has been causing all kinds of trouble within this package since we were extending from the `dist` directory. This finally moves the canonical TypeScript configuration to the root, so that we don't …

⬆️ Upgrade commitlint

---

README.md
src/api/commit.js
src/config/jest.config.js
src/scripts/__tests__/__snapshots__/commit-msg.js.snap
src/scripts/commit-msg.js

- Update `api/commit` type definitions to reflect _optional_ options in `ls.dirs`
- Prevent **commitlint** from ever type-checking configuration
- Ensure **ts-jest** escape hatch works with latest version of **ts-jest**
- Update Jest documentation to reflect new default **@swc-node/jest** transform

🐛 Post 7.0 fixes
